In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.precision', 2)
pd.options.display.float_format = '{:.2f}'.format
df = pd.read_csv("../data/interim/demo_h_columnas.csv")


def contar_nulos(df, columna):
    """
    Cuenta y muestra los valores faltantes en una columna 
    """
    total_nulos = df[columna].isnull().sum()
    print(f"Valores faltantes en {columna}: {total_nulos}")
    return total_nulos

def analizar_columna(df, columna):
    """
    Muestra estadísticas descriptivas y conteo de valores para una columna
    """
    print(f"--- Resumen de: {columna} ---")
    print("\n📊 Estadísticas Descriptivas:")
    print(df[columna].describe())
    
    print("\n🔢 Conteo de Valores (Frecuencias):")
    print(df[columna].value_counts())
    print("-" * 30)


df.head()

,SEQN,RIAGENDR,RIDAGEYR,RIDRETH3,DMDEDUC2,DMDMARTL,INDFMPIR,DMQMILIZ
0,73557.00,1.00,69.00,4.00,3.00,4.00,0.84,1.00
1,73558.00,1.00,54.00,3.00,3.00,1.00,1.78,2.00
2,73559.00,1.00,72.00,3.00,4.00,1.00,4.51,1.00
3,73560.00,1.00,9.00,3.00,NaN,NaN,2.52,NaN
4,73561.00,2.00,73.00,3.00,5.00,1.00,5.00,2.00

In [2]:
mapeo_nombres = {
    "SEQN": "ID",
    "RIAGENDR": "Genero",
    "RIDAGEYR": "Edad",
    "RIDRETH3": "Etnia",
    "DMDEDUC2": "Nivel_Educativo",
    "DMDMARTL": "Estado_Civil",
    "INDFMPIR": "Ratio_Pobreza",
    "DMQMILIZ": "Servicio_Militar"
}

df = df.rename(columns=mapeo_nombres)

df.head()

,ID,Genero,Edad,Etnia,Nivel_Educativo,Estado_Civil,Ratio_Pobreza,Servicio_Militar
0,73557.00,1.00,69.00,4.00,3.00,4.00,0.84,1.00
1,73558.00,1.00,54.00,3.00,3.00,1.00,1.78,2.00
2,73559.00,1.00,72.00,3.00,4.00,1.00,4.51,1.00
3,73560.00,1.00,9.00,3.00,NaN,NaN,2.52,NaN
4,73561.00,2.00,73.00,3.00,5.00,1.00,5.00,2.00

### Mapeo de numeros a columnas (opcional) (one-hot enconding)

In [ ]:
### Mapeo de numeros a columnas (opcional) (one-hot enconding)

mapeo_etnia = {
    1: "Mexicano_Americano",
    2: "Otro_Hispano",
    3: "Blanco_No_Hispano",
    4: "Negro_No_Hispano",
    6: "Asiatico_No_Hispano",
    7: "Otra_Raza_Multi"
}

df['Etnia'] = df['Etnia'].map(mapeo_etnia)

# mapeo de atributos a columnas True o False
df = pd.get_dummies(df, columns=['Etnia'], prefix='Etnia')

df.head()

,ID,Genero,Edad,Nivel_Educativo,Estado_Civil,Ratio_Pobreza,Servicio_Militar,Etnia_Asiatico_No_Hispano,Etnia_Blanco_No_Hispano,Etnia_Mexicano_Americano,Etnia_Negro_No_Hispano,Etnia_Otra_Raza_Multi,Etnia_Otro_Hispano
0,73557.00,1.00,69.00,3.00,4.00,0.84,1.00,False,False,False,True,False,False
1,73558.00,1.00,54.00,3.00,1.00,1.78,2.00,False,True,False,False,False,False
2,73559.00,1.00,72.00,4.00,1.00,4.51,1.00,False,True,False,False,False,False
3,73560.00,1.00,9.00,NaN,NaN,2.52,NaN,False,True,False,False,False,False
4,73561.00,2.00,73.00,5.00,1.00,5.00,2.00,False,True,False,False,False,False

## Limpieza de edad

### Revisar nulos

In [4]:
total_nulos = df['Edad'].isnull().sum()
print(f"Valores faltantes en Edad: {total_nulos}")

Valores faltantes en Edad: 0

### Convertir floats a enteros

In [5]:
df["Edad"] = df["Edad"].apply(np.floor).astype("Int64")
df["Edad"] = df["Edad"].astype("Int64")
# porcentajes
df["Edad"].value_counts(normalize=True) * 100

Edad
0    3.98
80   3.46
2    2.73
1    2.57
6    2.57
     ...
76   0.50
75   0.50
77   0.37
78   0.35
79   0.29
Name: proportion, Length: 81, dtype: Float64

In [6]:
df["Edad"].describe()

count   10175.00
mean       31.48
std        24.42
min         0.00
25%        10.00
50%        26.00
75%        52.00
max        80.00
Name: Edad, dtype: Float64

## Limpieza de Nivel_Educativo

In [7]:
print(df["Nivel_Educativo"].describe())
print(df["Nivel_Educativo"].value_counts())

count   5769.00
mean       3.52
std        1.24
min        1.00
25%        3.00
50%        4.00
75%        5.00
max        9.00
Name: Nivel_Educativo, dtype: float64
Nivel_Educativo
4.00    1770
5.00    1443
3.00    1303
2.00     791
1.00     455
9.00       5
7.00       2
Name: count, dtype: int64

In [8]:
# Reemplazar los valores 7 y 9 por 0
df["Nivel_Educativo"] = df["Nivel_Educativo"].replace({7.0: 0, 9.0: 0})

In [9]:
print(df["Nivel_Educativo"].value_counts())

Nivel_Educativo
4.00    1770
5.00    1443
3.00    1303
2.00     791
1.00     455
0.00       7
Name: count, dtype: int64

In [10]:
contar_nulos(df,"Nivel_Educativo")
# Reemplazar todos los nulos por 0
df["Nivel_Educativo"] = df["Nivel_Educativo"].fillna(0)

contar_nulos(df,"Nivel_Educativo")

df["Nivel_Educativo"] = df["Nivel_Educativo"].astype(int)
print(df["Nivel_Educativo"].value_counts())

Valores faltantes en Nivel_Educativo: 4406
Valores faltantes en Nivel_Educativo: 0
Nivel_Educativo
0    4413
4    1770
5    1443
3    1303
2     791
1     455
Name: count, dtype: int64

## Limpieza de Estado_Civil

In [11]:
analizar_columna(df,"Estado_Civil")

--- Resumen de: Estado_Civil ---

📊 Estadísticas Descriptivas:
count   5769.00
mean       2.57
std        2.63
min        1.00
25%        1.00
50%        1.00
75%        5.00
max       99.00
Name: Estado_Civil, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Estado_Civil
1.00     2965
5.00     1112
3.00      659
2.00      436
6.00      417
4.00      177
77.00       2
99.00       1
Name: count, dtype: int64
------------------------------

In [12]:
contar_nulos(df,"Estado_Civil")

Valores faltantes en Estado_Civil: 4406

np.int64(4406)

### Limpiar nulos y 77, 99

In [13]:
# Reemplazar los valores 77 y 99 por 0
df["Estado_Civil"] = df["Estado_Civil"].replace({77.0: 0, 99.0: 0})

# Llenar los nulos con 0
df["Estado_Civil"] = df["Estado_Civil"].fillna(0)

# Convertir a entero 
df["Estado_Civil"] = df["Estado_Civil"].astype(int)

In [14]:
analizar_columna(df,"Estado_Civil")

--- Resumen de: Estado_Civil ---

📊 Estadísticas Descriptivas:
count   10175.00
mean        1.43
std         1.86
min         0.00
25%         0.00
50%         1.00
75%         2.00
max         6.00
Name: Estado_Civil, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Estado_Civil
0    4409
1    2965
5    1112
3     659
2     436
6     417
4     177
Name: count, dtype: int64
------------------------------

## Limpieza de Servicio_Militar

In [15]:
analizar_columna(df,"Servicio_Militar")

--- Resumen de: Servicio_Militar ---

📊 Estadísticas Descriptivas:
count   6261.00
mean       1.91
std        0.29
min        1.00
25%        2.00
50%        2.00
75%        2.00
max        7.00
Name: Servicio_Militar, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Servicio_Militar
2.00    5717
1.00     543
7.00       1
Name: count, dtype: int64
------------------------------

In [ ]:
contar_nulos(df,"Servicio_Militar")

In [20]:
# Reemplazar los valores 7 por 0
df["Servicio_Militar"] = df["Servicio_Militar"].replace({7: 0})

# Llenar los nulos con 0
df["Servicio_Militar"] = df["Servicio_Militar"].fillna(0)

# Convertir a entero
df["Servicio_Militar"] = df["Servicio_Militar"].astype(int)

In [29]:
contar_nulos(df,"Servicio_Militar")

Valores faltantes en Servicio_Militar: 0

np.int64(0)

## Limpieza de Ratio Pobreza

In [17]:
analizar_columna(df,'Ratio_Pobreza')

--- Resumen de: Ratio_Pobreza ---

📊 Estadísticas Descriptivas:
count   9390.00
mean       2.25
std        1.63
min        0.00
25%        0.87
50%        1.71
75%        3.61
max        5.00
Name: Ratio_Pobreza, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Ratio_Pobreza
5.00    1416
1.27     151
0.00     105
0.54      77
0.63      74
        ...
2.91       1
1.90       1
3.11       1
2.17       1
3.62       1
Name: count, Length: 440, dtype: int64
------------------------------

In [23]:
contar_nulos(df,'Ratio_Pobreza')

Valores faltantes en Ratio_Pobreza: 785

np.int64(785)

Rellnar los nulos con 0 no es correcto, puesto que los nulos son falta de informacion y 0 tiene un significado real.  

INDFMPIR: This variable is the ratio of family income to poverty. The Department of Health and Human Services (HHS) poverty guidelines were used as the poverty measure to calculate this ratio. These guidelines are issued each year, in the Federal Register, for determining financial eligibility for certain federal programs, such as Head Start, Supplemental Nutrition Assistance Program (SNAP), Special Supplemental Nutrition Program for Women, Infants, and Children (WIC), and the National School Lunch Program. The poverty guidelines vary by family size and geographic location (with different guidelines for the 48 contiguous states and the District of Columbia; Alaska; and Hawaii).

INDFMPIR was calculated by dividing family (or individual) income by the poverty guidelines specific to the survey year. The value was not computed if the respondent only reported income as < $20,000 or ≥ $20,000. If family income was reported as a more detailed category, the midpoint of the range was used to compute the ratio. Values at or above 5.00 were coded as 5.00 or more because of disclosure concerns. The values were not computed if the income data was missing.

In [24]:
# Crear una columna bandera (1 si era nulo, 0 si no)
df["Ratio_Pobreza_Faltante"] = df["Ratio_Pobreza"].isnull().astype(int)

In [25]:
# Rellenar el nulo con la mediana
mediana_pobreza = df["Ratio_Pobreza"].median()
df["Ratio_Pobreza"] = df["Ratio_Pobreza"].fillna(mediana_pobreza)

In [28]:
analizar_columna(df,'Ratio_Pobreza')

--- Resumen de: Ratio_Pobreza ---

📊 Estadísticas Descriptivas:
count   10175.00
mean        2.21
std         1.58
min         0.00
25%         0.93
50%         1.71
75%         3.40
max         5.00
Name: Ratio_Pobreza, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Ratio_Pobreza
5.00    1416
1.71     785
1.27     151
0.00     105
0.54      77
        ...
2.91       1
1.90       1
3.11       1
2.17       1
3.62       1
Name: count, Length: 441, dtype: int64
------------------------------