In [1]:
import pandas as pd
import numpy as np



def contar_nulos(df, columna):
    """
    Cuenta y muestra los valores faltantes en una columna 
    """
    total_nulos = df[columna].isnull().sum()
    print(f"Valores faltantes en {columna}: {total_nulos}")
    return total_nulos

def analizar_columna(df, columna):
    """
    Muestra estadísticas descriptivas y conteo de valores para una columna
    """
    print(f"--- Resumen de: {columna} ---")
    print("\n📊 Estadísticas Descriptivas:")
    print(df[columna].describe())
    
    print("\n🔢 Conteo de Valores (Frecuencias):")
    print(df[columna].value_counts())
    print("-" * 30)

# Limpieza Demo_H

In [2]:
df = pd.read_csv("../data/interim/demo_h_columnas.csv")

mapeo_nombres = {
    "SEQN": "ID",
    "RIAGENDR": "Genero",
    "RIDAGEYR": "Edad",
    "RIDRETH3": "Etnia",
    "DMDEDUC2": "Nivel_Educativo",
    "DMDMARTL": "Estado_Civil",
    "INDFMPIR": "Ratio_Pobreza",
    "DMQMILIZ": "Servicio_Militar"
}

df = df.rename(columns=mapeo_nombres)

df.head()

,ID,Genero,Edad,Etnia,Nivel_Educativo,Estado_Civil,Ratio_Pobreza,Servicio_Militar
0,73557.0,1.0,69.0,4.0,3.0,4.0,0.84,1.0
1,73558.0,1.0,54.0,3.0,3.0,1.0,1.78,2.0
2,73559.0,1.0,72.0,3.0,4.0,1.0,4.51,1.0
3,73560.0,1.0,9.0,3.0,NaN,NaN,2.52,NaN
4,73561.0,2.0,73.0,3.0,5.0,1.0,5.00,2.0

### Mapeo de numeros a columnas (opcional) (one-hot enconding)

In [3]:
### Mapeo de numeros a columnas (opcional) (one-hot enconding)

mapeo_etnia = {
    1: "Mexicano_Americano",
    2: "Otro_Hispano",
    3: "Blanco_No_Hispano",
    4: "Negro_No_Hispano",
    6: "Asiatico_No_Hispano",
    7: "Otra_Raza_Multi"
}

df['Etnia'] = df['Etnia'].map(mapeo_etnia)

# mapeo de atributos a columnas True o False
df = pd.get_dummies(df, columns=['Etnia'], prefix='Etnia')

df.head()

,ID,Genero,Edad,Nivel_Educativo,Estado_Civil,Ratio_Pobreza,Servicio_Militar,Etnia_Asiatico_No_Hispano,Etnia_Blanco_No_Hispano,Etnia_Mexicano_Americano,Etnia_Negro_No_Hispano,Etnia_Otra_Raza_Multi,Etnia_Otro_Hispano
0,73557.0,1.0,69.0,3.0,4.0,0.84,1.0,False,False,False,True,False,False
1,73558.0,1.0,54.0,3.0,1.0,1.78,2.0,False,True,False,False,False,False
2,73559.0,1.0,72.0,4.0,1.0,4.51,1.0,False,True,False,False,False,False
3,73560.0,1.0,9.0,NaN,NaN,2.52,NaN,False,True,False,False,False,False
4,73561.0,2.0,73.0,5.0,1.0,5.00,2.0,False,True,False,False,False,False

## Limpieza de edad

### Revisar nulos

In [4]:
total_nulos = df['Edad'].isnull().sum()
print(f"Valores faltantes en Edad: {total_nulos}")

Valores faltantes en Edad: 0

### Convertir floats a enteros

In [5]:
df["Edad"] = df["Edad"].apply(np.floor).astype("Int64")
df["Edad"] = df["Edad"].astype("Int64")
# porcentajes
df["Edad"].value_counts(normalize=True) * 100

Edad
0     3.980344
80    3.459459
2     2.732187
1     2.574939
6     2.574939
        ...
76    0.501229
75    0.501229
77    0.373464
78    0.353808
79     0.29484
Name: proportion, Length: 81, dtype: Float64

In [6]:
df["Edad"].describe()

count      10175.0
mean     31.484128
std      24.421651
min            0.0
25%           10.0
50%           26.0
75%           52.0
max           80.0
Name: Edad, dtype: Float64

## Limpieza de Nivel_Educativo

In [7]:
print(df["Nivel_Educativo"].describe())
print(df["Nivel_Educativo"].value_counts())

count    5769.000000
mean        3.518807
std         1.236032
min         1.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         9.000000
Name: Nivel_Educativo, dtype: float64
Nivel_Educativo
4.0    1770
5.0    1443
3.0    1303
2.0     791
1.0     455
9.0       5
7.0       2
Name: count, dtype: int64

In [8]:
# Reemplazar los valores 7 y 9 por 0
df["Nivel_Educativo"] = df["Nivel_Educativo"].replace({7.0: 0, 9.0: 0})

In [9]:
print(df["Nivel_Educativo"].value_counts())

Nivel_Educativo
4.0    1770
5.0    1443
3.0    1303
2.0     791
1.0     455
0.0       7
Name: count, dtype: int64

In [10]:
contar_nulos(df,"Nivel_Educativo")
# Reemplazar todos los nulos por 0
df["Nivel_Educativo"] = df["Nivel_Educativo"].fillna(0)

contar_nulos(df,"Nivel_Educativo")

df["Nivel_Educativo"] = df["Nivel_Educativo"].astype(int)
print(df["Nivel_Educativo"].value_counts())

Valores faltantes en Nivel_Educativo: 4406
Valores faltantes en Nivel_Educativo: 0
Nivel_Educativo
0    4413
4    1770
5    1443
3    1303
2     791
1     455
Name: count, dtype: int64

## Limpieza de Estado_Civil

In [11]:
analizar_columna(df,"Estado_Civil")

--- Resumen de: Estado_Civil ---

📊 Estadísticas Descriptivas:
count    5769.000000
mean        2.571850
std         2.626299
min         1.000000
25%         1.000000
50%         1.000000
75%         5.000000
max        99.000000
Name: Estado_Civil, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Estado_Civil
1.0     2965
5.0     1112
3.0      659
2.0      436
6.0      417
4.0      177
77.0       2
99.0       1
Name: count, dtype: int64
------------------------------

In [12]:
contar_nulos(df,"Estado_Civil")

Valores faltantes en Estado_Civil: 4406

np.int64(4406)

### Limpiar nulos y 77, 99

In [13]:
# Reemplazar los valores 77 y 99 por 0
df["Estado_Civil"] = df["Estado_Civil"].replace({77.0: 0, 99.0: 0})

# Llenar los nulos con 0
df["Estado_Civil"] = df["Estado_Civil"].fillna(0)

# Convertir a entero 
df["Estado_Civil"] = df["Estado_Civil"].astype(int)

In [14]:
analizar_columna(df,"Estado_Civil")

--- Resumen de: Estado_Civil ---

📊 Estadísticas Descriptivas:
count    10175.000000
mean         1.433317
std          1.864817
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          6.000000
Name: Estado_Civil, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Estado_Civil
0    4409
1    2965
5    1112
3     659
2     436
6     417
4     177
Name: count, dtype: int64
------------------------------

## Limpieza de Servicio_Militar

In [15]:
analizar_columna(df,"Servicio_Militar")

--- Resumen de: Servicio_Militar ---

📊 Estadísticas Descriptivas:
count    6261.000000
mean        1.914071
std         0.288704
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         7.000000
Name: Servicio_Militar, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Servicio_Militar
2.0    5717
1.0     543
7.0       1
Name: count, dtype: int64
------------------------------

In [16]:
contar_nulos(df,"Servicio_Militar")

Valores faltantes en Servicio_Militar: 3914

np.int64(3914)

In [17]:
# Reemplazar los valores 7 por 0
df["Servicio_Militar"] = df["Servicio_Militar"].replace({7: 0})

# Llenar los nulos con 0
df["Servicio_Militar"] = df["Servicio_Militar"].fillna(0)

# Convertir a entero
df["Servicio_Militar"] = df["Servicio_Militar"].astype(int)

In [18]:
contar_nulos(df,"Servicio_Militar")

Valores faltantes en Servicio_Militar: 0

np.int64(0)

## Limpieza de Ratio Pobreza

In [19]:
analizar_columna(df,'Ratio_Pobreza')

--- Resumen de: Ratio_Pobreza ---

📊 Estadísticas Descriptivas:
count    9.390000e+03
mean     2.252153e+00
std      1.634907e+00
min      5.397605e-79
25%      8.700000e-01
50%      1.705000e+00
75%      3.607500e+00
max      5.000000e+00
Name: Ratio_Pobreza, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Ratio_Pobreza
5.000000e+00    1416
1.270000e+00     151
5.397605e-79     105
5.400000e-01      77
6.300000e-01      74
                ...
2.910000e+00       1
1.900000e+00       1
3.110000e+00       1
2.170000e+00       1
3.620000e+00       1
Name: count, Length: 440, dtype: int64
------------------------------

In [20]:
contar_nulos(df,'Ratio_Pobreza')

Valores faltantes en Ratio_Pobreza: 785

np.int64(785)

Rellnar los nulos con 0 no es correcto, puesto que los nulos son falta de informacion y 0 tiene un significado real.  

INDFMPIR: This variable is the ratio of family income to poverty. The Department of Health and Human Services (HHS) poverty guidelines were used as the poverty measure to calculate this ratio. These guidelines are issued each year, in the Federal Register, for determining financial eligibility for certain federal programs, such as Head Start, Supplemental Nutrition Assistance Program (SNAP), Special Supplemental Nutrition Program for Women, Infants, and Children (WIC), and the National School Lunch Program. The poverty guidelines vary by family size and geographic location (with different guidelines for the 48 contiguous states and the District of Columbia; Alaska; and Hawaii).

INDFMPIR was calculated by dividing family (or individual) income by the poverty guidelines specific to the survey year. The value was not computed if the respondent only reported income as < $20,000 or ≥ $20,000. If family income was reported as a more detailed category, the midpoint of the range was used to compute the ratio. Values at or above 5.00 were coded as 5.00 or more because of disclosure concerns. The values were not computed if the income data was missing.

In [21]:
# Crear una columna bandera (1 si era nulo, 0 si no)
df["Ratio_Pobreza_Faltante"] = df["Ratio_Pobreza"].isnull().astype(int)

In [22]:
# Rellenar el nulo con la mediana
mediana_pobreza = df["Ratio_Pobreza"].median()
df["Ratio_Pobreza"] = df["Ratio_Pobreza"].fillna(mediana_pobreza)

In [23]:
analizar_columna(df,'Ratio_Pobreza')

--- Resumen de: Ratio_Pobreza ---

📊 Estadísticas Descriptivas:
count    1.017500e+04
mean     2.209941e+00
std      1.577340e+00
min      5.397605e-79
25%      9.300000e-01
50%      1.705000e+00
75%      3.400000e+00
max      5.000000e+00
Name: Ratio_Pobreza, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Ratio_Pobreza
5.000000e+00    1416
1.705000e+00     785
1.270000e+00     151
5.397605e-79     105
5.400000e-01      77
                ...
2.910000e+00       1
1.900000e+00       1
3.110000e+00       1
2.170000e+00       1
3.620000e+00       1
Name: count, Length: 441, dtype: int64
------------------------------

# Limpieza ALQ

In [24]:
df = pd.read_csv("../data/interim/alq_h_columnas.csv")

nuevos_nombres = {
    "ALQ120Q": "Frec_Consumo_Anual",
    "ALQ120U": "Unidad_Frec_Anual",
    "ALQ130":  "Promedio_Tragos_Dia",
    "ALQ141Q": "Dias_4_5_Tragos",
    "ALQ141U": "Unidad_4_5_Tragos", 
    "ALQ160":  "Dias_Con_+4_5_Tragos_En_2hrs"
}

# Aplicar el cambio
df = df.rename(columns=nuevos_nombres)
df.head()

,SEQN,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs
0,73557.0,1.000000e+00,3.0,1.0,5.397605e-79,NaN,NaN
1,73558.0,7.000000e+00,1.0,4.0,2.000000e+00,1.0,5.397605e-79
2,73559.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN
3,73561.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN
4,73562.0,5.000000e+00,3.0,1.0,5.397605e-79,NaN,5.397605e-79

Crearemos una sola columna Dias_Consumo_Anual para unir la frecuencia y el consumo

In [25]:
analizar_columna(df,'Frec_Consumo_Anual')
contar_nulos(df,'Frec_Consumo_Anual')

--- Resumen de: Frec_Consumo_Anual ---

📊 Estadísticas Descriptivas:
count    4.479000e+03
mean     4.709310e+00
std      3.442836e+01
min      5.397605e-79
25%      1.000000e+00
50%      2.000000e+00
75%      4.000000e+00
max      9.990000e+02
Name: Frec_Consumo_Anual, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Frec_Consumo_Anual
1.000000e+00    1046
2.000000e+00     884
5.397605e-79     882
3.000000e+00     524
4.000000e+00     302
5.000000e+00     265
7.000000e+00     194
6.000000e+00     141
1.000000e+01      70
2.000000e+01      24
1.200000e+01      24
8.000000e+00      23
1.500000e+01      22
3.000000e+01      20
1.400000e+01       6
3.650000e+02       6
9.000000e+00       4
9.990000e+02       4
2.500000e+01       4
2.400000e+01       4
4.000000e+01       2
8.000000e+01       2
1.100000e+01       2
1.600000e+01       2
1.000000e+02       2
2.800000e+01       2
5.200000e+01       1
2.000000e+02       1
9.000000e+01       1
3.000000e+02       1
1.800000e+01       1
3.500000e+02       1
1.700000e+01       1
3.050000e+02       1
1.820000e+02       1
4.500000e+01       1
1.600000e+02       1
9.600000e+01       1
1.300000e+01       1
1.120000e+02       1
6.100000e+01       1
1.800000e+02       1
1.200000e+02       1
3.500000e+01       1
Name: count, dtype: int64
------------------------------
Valores faltantes en Frec_Consumo_Anual: 1445

np.int64(1445)

### Limpieza de Frec_Consumo_Anual, Mantenemos nulos

In [53]:
# Quitamos 999 , mantenemos nulos
df["Frec_Consumo_Anual"] = df["Frec_Consumo_Anual"].replace({999: np.nan})
analizar_columna(df,'Frec_Consumo_Anual')
contar_nulos(df,'Frec_Consumo_Anual')

--- Resumen de: Frec_Consumo_Anual ---

📊 Estadísticas Descriptivas:
count    4475.000000
mean        3.820559
std        17.369714
min         0.000000
25%         1.000000
50%         2.000000
75%         4.000000
max       365.000000
Name: Frec_Consumo_Anual, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Frec_Consumo_Anual
1.0      1046
2.0       884
0.0       882
3.0       524
4.0       302
5.0       265
7.0       194
6.0       141
10.0       70
20.0       24
12.0       24
8.0        23
15.0       22
30.0       20
14.0        6
365.0       6
9.0         4
25.0        4
24.0        4
40.0        2
80.0        2
11.0        2
16.0        2
100.0       2
28.0        2
52.0        1
200.0       1
90.0        1
300.0       1
18.0        1
350.0       1
17.0        1
305.0       1
182.0       1
45.0        1
160.0       1
96.0        1
13.0        1
112.0       1
61.0        1
180.0       1
120.0       1
35.0        1
Name: count, dtype: int64
------------------------------
Valores faltantes en Frec_Consumo_Anual: 1449

np.int64(1449)

### Limpieza de Unidad_Frec_Anual

In [52]:
analizar_columna(df,'Unidad_Frec_Anual')
contar_nulos(df,'Unidad_Frec_Anual')

--- Resumen de: Unidad_Frec_Anual ---

📊 Estadísticas Descriptivas:
count    3593.000000
mean        1.921514
std         0.853701
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         3.000000
Name: Unidad_Frec_Anual, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Unidad_Frec_Anual
1.0    1461
3.0    1179
2.0     953
Name: count, dtype: int64
------------------------------
Valores faltantes en Unidad_Frec_Anual: 2331

np.int64(2331)

### Creacion de Dias_Consumo_Anual

In [34]:
factores = {1: 52, 2: 12, 3: 1}
df['Dias_Consumo_Anual'] = df['Frec_Consumo_Anual'] * df['Unidad_Frec_Anual'].map(factores)

# Como los que marcaron 0 no tienen unidad, el resultado da NaN, pero debería ser 0.
df['Frec_Consumo_Anual'] = df['Frec_Consumo_Anual'].round(2)

df.loc[df['Frec_Consumo_Anual'] == 0, 'Dias_Consumo_Anual'] = 0

df

,SEQN,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Dias_Consumo_Anual
0,73557.0,1.0,3.0,1.0,5.397605e-79,NaN,NaN,1.0
1,73558.0,7.0,1.0,4.0,2.000000e+00,1.0,5.397605e-79,364.0
2,73559.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0
3,73561.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0
4,73562.0,5.0,3.0,1.0,5.397605e-79,NaN,5.397605e-79,5.0
...,...,...,...,...,...,...,...,...
5919,83723.0,3.0,3.0,2.0,5.397605e-79,NaN,NaN,3.0
5920,83724.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0
5921,83726.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5922,83727.0,1.0,2.0,3.0,5.397605e-79,NaN,NaN,12.0
5923,83729.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Limpieza Promedio_Tragos Dia

In [ ]:
#  Reemplazar codigos de error por NaN
df["Promedio_Tragos_Dia"] = df["Promedio_Tragos_Dia"].replace({777: np.nan, 999: np.nan})

# Si alguien dijo que bebe 0 dias al año, su promedio de tragos al dia es 0
df['Frec_Consumo_Anual'] = df['Frec_Consumo_Anual'].round(2)
df.loc[df['Frec_Consumo_Anual'] == 0, 'Promedio_Tragos_Dia'] = 0

### Limpieza Dias_4_5_Tragos

In [50]:
df['Dias_4_5_Tragos'] = df['Dias_4_5_Tragos'].round(2)

# Si alguien no bebio, ponemos 0
df.loc[df['Frec_Consumo_Anual'] == 0, 'Dias_4_5_Tragos'] = 0

analizar_columna(df,'Dias_4_5_Tragos')
contar_nulos(df,'Dias_4_5_Tragos')

--- Resumen de: Dias_4_5_Tragos ---

📊 Estadísticas Descriptivas:
count    4477.00000
mean        3.26491
std        40.72344
min         0.00000
25%         0.00000
50%         0.00000
75%         1.00000
max       999.00000
Name: Dias_4_5_Tragos, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Dias_4_5_Tragos
0.0      3006
1.0       450
2.0       364
3.0       171
4.0       107
5.0       101
10.0       69
7.0        50
6.0        39
12.0       17
30.0       17
8.0        17
20.0       13
15.0       10
999.0       7
14.0        4
9.0         4
25.0        3
24.0        3
350.0       2
40.0        2
100.0       2
16.0        2
21.0        1
150.0       1
78.0        1
13.0        1
45.0        1
18.0        1
60.0        1
52.0        1
11.0        1
305.0       1
96.0        1
72.0        1
17.0        1
62.0        1
104.0       1
61.0        1
50.0        1
Name: count, dtype: int64
------------------------------
Valores faltantes en Dias_4_5_Tragos: 1447

np.int64(1447)

### Limpieza Unidad_4_5_Tragos

In [ ]:
df['Unidad_4_5_Tragos'] = df['Unidad_4_5_Tragos'].round(2)
analizar_columna(df,'Unidad_4_5_Tragos')
contar_nulos(df,'Unidad_4_5_Tragos')

# Si no tomo 4-5 tragos en un dia, su unidad es 0
df.loc[df['Dias_4_5_Tragos'] == 0, 'Unidad_4_5_Tragos'] = 0
# Si no tomo, unidad es 0
df.loc[df['Frec_Consumo_Anual'] == 0, 'Unidad_4_5_Tragos'] = 0
df

--- Resumen de: Unidad_4_5_Tragos ---

📊 Estadísticas Descriptivas:
count    2346.000000
mean        1.451833
std         1.309805
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max         3.000000
Name: Unidad_4_5_Tragos, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Unidad_4_5_Tragos
0.0    882
3.0    839
1.0    361
2.0    264
Name: count, dtype: int64
------------------------------
Valores faltantes en Unidad_4_5_Tragos: 3578

,SEQN,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Dias_Consumo_Anual
0,73557.0,1.0,3.0,1.0,0.0,NaN,NaN,1.0
1,73558.0,7.0,1.0,4.0,2.0,1.0,5.397605e-79,364.0
2,73559.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0
3,73561.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0
4,73562.0,5.0,3.0,1.0,0.0,NaN,5.397605e-79,5.0
...,...,...,...,...,...,...,...,...
5919,83723.0,3.0,3.0,2.0,0.0,NaN,NaN,3.0
5920,83724.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0
5921,83726.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5922,83727.0,1.0,2.0,3.0,0.0,NaN,NaN,12.0
5923,83729.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN