### Limpieza SMQ_H

In [36]:
import pandas as pd
import numpy as np
# Cargar archivo con columnas SMQ seleccionadas
smq = pd.read_csv("../data/interim/smq_h_columnas.csv")

# Vista inicial
smq.head()

,SEQN,SMQ040,SMD641,SMD650,SMQ078,SMQ020,SMQ621,SMD630,SMD030,SMQ670,SMQ848,SMQ852Q,SMQ852U
0,73557.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,1.700000e+01,NaN,NaN,NaN,NaN
1,73558.0,2.0,1.0,1.0,NaN,1.0,NaN,NaN,5.397605e-79,2.0,NaN,NaN,NaN
2,73559.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,2.000000e+01,NaN,NaN,NaN,NaN
3,73561.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73562.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,1.800000e+01,NaN,NaN,NaN,NaN

In [37]:
SMQ_COLS = [
    "SEQN",
    "SMQ040",
    "SMD641",
    "SMD650",
    "SMQ078",
    "SMQ020",
    "SMQ621",
    "SMD630",
    "SMD030",
    "SMQ670",
    "SMQ848",
    "SMQ852Q",
    "SMQ852U"
]

smq = smq[SMQ_COLS].copy()
smq.head()

,SEQN,SMQ040,SMD641,SMD650,SMQ078,SMQ020,SMQ621,SMD630,SMD030,SMQ670,SMQ848,SMQ852Q,SMQ852U
0,73557.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,1.700000e+01,NaN,NaN,NaN,NaN
1,73558.0,2.0,1.0,1.0,NaN,1.0,NaN,NaN,5.397605e-79,2.0,NaN,NaN,NaN
2,73559.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,2.000000e+01,NaN,NaN,NaN,NaN
3,73561.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73562.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,1.800000e+01,NaN,NaN,NaN,NaN

In [38]:
codigos_invalidos = [7, 9, 77, 99, 777, 999, 7777, 9999]
smq.replace(codigos_invalidos, np.nan, inplace=True)

smq.isna().sum()

SEQN          0
SMQ040     4589
SMD641     5861
SMD650     5971
SMQ078     6214
SMQ020     1057
SMQ621     6174
SMD630     7086
SMD030     4634
SMQ670     5907
SMQ848     6592
SMQ852Q    6619
SMQ852U    6591
dtype: int64

In [39]:
for col in smq.columns:
    if col != "SEQN":
        smq[col] = pd.to_numeric(smq[col], errors="coerce")

smq.dtypes

SEQN       float64
SMQ040     float64
SMD641     float64
SMD650     float64
SMQ078     float64
SMQ020     float64
SMQ621     float64
SMD630     float64
SMD030     float64
SMQ670     float64
SMQ848     float64
SMQ852Q    float64
SMQ852U    float64
dtype: object

In [40]:
cols_binarias = ["SMQ020", "SMQ670"]

for col in cols_binarias:
    smq[col] = smq[col].map({1: 1, 2: 0})

smq[cols_binarias].head()

   SMQ020  SMQ670
0     1.0     NaN
1     1.0     0.0
2     1.0     NaN
3     0.0     NaN
4     1.0     NaN

In [41]:
smq.loc[(smq["SMD641"] < 0) | (smq["SMD641"] > 30), "SMD641"] = np.nan
smq.loc[(smq["SMD650"] < 1) | (smq["SMD650"] > 95), "SMD650"] = np.nan
smq.loc[(smq["SMD630"] < 6) | (smq["SMD630"] > 19), "SMD630"] = np.nan
smq.loc[(smq["SMD030"] < 0) | (smq["SMD030"] > 80), "SMD030"] = np.nan
smq.loc[(smq["SMQ848"] < 1) | (smq["SMQ848"] > 20), "SMQ848"] = np.nan
smq.loc[(smq["SMQ852Q"] < 0) | (smq["SMQ852Q"] > 356), "SMQ852Q"] = np.nan

smq.describe()

,SEQN,SMQ040,SMD641,SMD650,SMQ078,SMQ020,SMQ621,SMD630,SMD030,SMQ670,SMQ848,SMQ852Q,SMQ852U
count,7168.000000,2579.000000,1.307000e+03,1197.000000,954.000000,6111.000000,994.000000,82.000000,2.534000e+03,1261.000000,576.000000,5.490000e+02,577.000000
mean,78676.884068,2.137650,2.444453e+01,10.529657,2.380503,0.422026,1.367203,13.865854,1.725770e+01,0.475813,3.302083,4.493625e+00,1.786828
std,2925.217462,0.942517,1.002832e+01,8.575467,1.228755,0.493923,1.093315,2.023090,6.376920e+00,0.499613,3.641175,1.614280e+01,0.846541
min,73557.000000,1.000000,5.397605e-79,1.000000,1.000000,0.000000,1.000000,6.000000,5.397605e-79,0.000000,1.000000,5.397605e-79,1.000000
25%,76157.750000,1.000000,2.450000e+01,4.000000,1.000000,0.000000,1.000000,13.000000,1.500000e+01,0.000000,1.000000,1.000000e+00,1.000000
50%,78718.500000,3.000000,3.000000e+01,10.000000,2.000000,0.000000,1.000000,14.000000,1.700000e+01,0.000000,2.000000,2.000000e+00,2.000000
75%,81202.250000,3.000000,3.000000e+01,15.000000,3.000000,1.000000,1.000000,15.000000,2.000000e+01,1.000000,4.000000,4.000000e+00,3.000000
max,83729.000000,3.000000,3.000000e+01,90.000000,6.000000,1.000000,8.000000,17.000000,6.400000e+01,1.000000,20.000000,3.560000e+02,3.000000

In [43]:
for col in smq.columns:
    if col != "SEQN":
        if smq[col].dropna().nunique() == 2:
            smq[col] = smq[col].fillna(smq[col].mode()[0])
        else:
            smq[col] = smq[col].fillna(smq[col].median())

smq.isna().sum()

SEQN       0
SMQ040     0
SMD641     0
SMD650     0
SMQ078     0
SMQ020     0
SMQ621     0
SMD630     0
SMD030     0
SMQ670     0
SMQ848     0
SMQ852Q    0
SMQ852U    0
dtype: int64

In [44]:
import os

# Crear carpeta si no existe
os.makedirs("../data/processed", exist_ok=True)

# Guardar archivo limpio
smq.to_csv("../data/processed/smq_limpio.csv", index=False)

print("SMQ limpio guardado en data/processed/smq_limpio.csv")

SMQ limpio guardado en data/processed/smq_limpio.csv

### Limpieza OCQ_H

In [9]:
# Cargar datos OCQ
ocq = pd.read_csv("../data/interim/ocq_h_columnas.csv")

ocq.head()

,SEQN,OCQ180,OCQ210,OCD231,OCD241,OCQ260,OCD390G,OCD391,OCD392,OCD395
0,73557.0,NaN,NaN,NaN,NaN,NaN,1.0,10.0,16.0,204.0
1,73558.0,50.0,NaN,8.0,16.0,1.0,2.0,NaN,NaN,NaN
2,73559.0,NaN,NaN,NaN,NaN,NaN,1.0,21.0,2.0,216.0
3,73561.0,NaN,NaN,NaN,NaN,NaN,1.0,15.0,8.0,372.0
4,73562.0,56.0,NaN,9.0,17.0,2.0,2.0,NaN,NaN,NaN

In [12]:
OCQ_COLS = [
    "SEQN",
    "OCQ180",   # Horas trabajadas la semana pasada
    "OCQ210",   # Trabaja ≥35h (1=Sí, 2=No)
    "OCD231",   # Industria actual
    "OCD241",   # Ocupación actual
    "OCQ260",   # Tipo de empleo
    "OCD390G",  # Tipo de trabajo más largo
    "OCD391",   # Industria trabajo más largo
    "OCD392",   # Ocupación trabajo más largo
    "OCD395"    # Meses en el trabajo más largo
]

ocq = ocq[OCQ_COLS].copy()
ocq.head()

,SEQN,OCQ180,OCQ210,OCD231,OCD241,OCQ260,OCD390G,OCD391,OCD392,OCD395
0,73557.0,NaN,NaN,NaN,NaN,NaN,1.0,10.0,16.0,204.0
1,73558.0,50.0,NaN,8.0,16.0,1.0,2.0,NaN,NaN,NaN
2,73559.0,NaN,NaN,NaN,NaN,NaN,1.0,21.0,2.0,216.0
3,73561.0,NaN,NaN,NaN,NaN,NaN,1.0,15.0,8.0,372.0
4,73562.0,56.0,NaN,NaN,17.0,2.0,2.0,NaN,NaN,NaN

In [10]:
codigos_invalidos = [7, 9, 77, 99, 777, 999, 77777, 99999]
ocq.replace(codigos_invalidos, np.nan, inplace=True)

ocq.isna().sum()

SEQN          1
OCQ180     3141
OCQ210     5457
OCD231     3274
OCD241     3119
OCQ260     3025
OCD390G      16
OCD391     3249
OCD392     3101
OCD395     3046
dtype: int64

In [13]:
for col in ocq.columns:
    if col != "SEQN":
        ocq[col] = pd.to_numeric(ocq[col], errors="coerce")

ocq.dtypes

SEQN       float64
OCQ180     float64
OCQ210     float64
OCD231     float64
OCD241     float64
OCQ260     float64
OCD390G    float64
OCD391     float64
OCD392     float64
OCD395     float64
dtype: object

In [14]:
ocq["OCQ210"] = ocq["OCQ210"].map({1: 1, 2: 0})

ocq["OCQ210"].value_counts(dropna=False)

OCQ210
NaN    5457
0.0     693
1.0     314
Name: count, dtype: int64

In [15]:
ocq.loc[(ocq["OCQ180"] < 1) | (ocq["OCQ180"] > 120), "OCQ180"] = np.nan
ocq.loc[(ocq["OCD231"] < 1) | (ocq["OCD231"] > 22), "OCD231"] = np.nan
ocq.loc[(ocq["OCD241"] < 1) | (ocq["OCD241"] > 23), "OCD241"] = np.nan
ocq.loc[(ocq["OCQ260"] < 1) | (ocq["OCQ260"] > 6), "OCQ260"] = np.nan
ocq.loc[(ocq["OCD390G"] < 1) | (ocq["OCD390G"] > 4), "OCD390G"] = np.nan
ocq.loc[(ocq["OCD391"] < 1) | (ocq["OCD391"] > 22), "OCD391"] = np.nan
ocq.loc[(ocq["OCD392"] < 1) | (ocq["OCD392"] > 23), "OCD392"] = np.nan
ocq.loc[(ocq["OCD395"] < 0) | (ocq["OCD395"] > 720), "OCD395"] = np.nan

ocq.describe()

,SEQN,OCQ180,OCQ210,OCD231,OCD241,OCQ260,OCD390G,OCD391,OCD392,OCD395
count,6463.000000,3323.000000,1007.000000,3190.000000,3345.000000,3439.000000,6448.000000,3215.000000,3363.000000,3.418000e+03
mean,78683.017175,39.532651,0.311817,12.336364,13.275037,1.511195,1.654932,11.919129,14.306869,1.767651e+02
std,2923.858649,14.724085,0.463466,5.294171,6.510641,1.191071,0.874223,5.788509,6.121254,1.497085e+02
min,73557.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.397605e-79
25%,76175.000000,32.000000,0.000000,8.000000,10.000000,1.000000,1.000000,6.000000,11.000000,4.800000e+01
50%,78736.000000,40.000000,0.000000,14.000000,15.000000,1.000000,1.000000,13.000000,16.000000,1.320000e+02
75%,81203.500000,47.000000,1.000000,16.000000,17.000000,1.000000,2.000000,16.000000,19.000000,2.760000e+02
max,83729.000000,120.000000,1.000000,22.000000,23.000000,6.000000,4.000000,22.000000,23.000000,7.200000e+02

In [45]:
# Variables continuas
vars_continuas = ["OCQ180", "OCD395"]

# Variables categóricas
vars_categoricas = [
    "OCQ210", "OCD231", "OCD241",
    "OCQ260", "OCD390G", "OCD391", "OCD392"
]

# Imputación SIN inplace (forma correcta)
for col in vars_continuas:
    ocq[col] = ocq[col].fillna(ocq[col].median())

for col in vars_categoricas:
    ocq[col] = ocq[col].fillna(ocq[col].mode()[0])

ocq.isna().sum()

SEQN       1
OCQ180     0
OCQ210     0
OCD231     0
OCD241     0
OCQ260     0
OCD390G    0
OCD391     0
OCD392     0
OCD395     0
dtype: int64

In [46]:
import os

os.makedirs("../data/processed", exist_ok=True)

ocq.to_csv("../data/processed/ocq_limpio.csv", index=False)

print("OCQ limpio guardado correctamente en data/processed/ocq_limpio.csv")

OCQ limpio guardado correctamente en data/processed/ocq_limpio.csv

### Limpieza DLQ_H

In [18]:
# ==========================================
# LIMPIEZA DLQ (Discapacidades y dificultades)
# ==========================================

import pandas as pd
import numpy as np
from pathlib import Path

# 1) Cargar dataset y seleccionar columnas relevantes
dlq = pd.read_csv("../data/interim/dlq_h_columnas.csv")

DLQ_COLS = [
    "SEQN",
    "DLQ010",  # Dificultad para oír
    "DLQ020",  # Dificultad para ver
    "DLQ040",  # Dificultad para concentrarse/recordar
    "DLQ050",  # Dificultad para caminar/escaleras
    "DLQ060",  # Dificultad para vestirse/bañarse
    "DLQ080"   # Dificultad para hacer mandados solo
]

dlq = dlq[DLQ_COLS].copy()
dlq.head()

      SEQN  DLQ010  DLQ020  DLQ040  DLQ050  DLQ060  DLQ080
0  73557.0     2.0     2.0     2.0     2.0     2.0     2.0
1  73558.0     2.0     2.0     2.0     2.0     2.0     2.0
2  73559.0     1.0     2.0     2.0     2.0     2.0     2.0
3  73560.0     2.0     2.0     2.0     2.0     2.0     NaN
4  73561.0     2.0     2.0     2.0     2.0     2.0     2.0

In [19]:
# 2) Reemplazar códigos inválidos NHANES (Refused / Don't know)
dlq.replace([7, 9], np.nan, inplace=True)

In [20]:
# 3) Convertir variables a numérico
for col in DLQ_COLS:
    if col != "SEQN":
        dlq[col] = pd.to_numeric(dlq[col], errors="coerce")

In [21]:
# 4) Binarizar variables (Sí=1, No=0)
for col in DLQ_COLS:
    if col != "SEQN":
        dlq[col] = dlq[col].map({1: 1, 2: 0})

In [47]:
# 5) Imputación de valores faltantes
# Como todas son binarias → usar MODA
for col in DLQ_COLS:
    if col != "SEQN":
        if dlq[col].dropna().nunique() > 0:
            moda = dlq[col].mode()[0]
            dlq[col] = dlq[col].fillna(moda)

In [23]:
# 6) Crear carpeta processed si no existe
output_path = Path("../data/processed")
output_path.mkdir(parents=True, exist_ok=True)

In [24]:
# 7) Guardar dataset limpio
dlq.to_csv(output_path / "dlq_limpio.csv", index=False)

print("✅ DLQ limpio guardado en data/processed/dlq_limpio.csv")
dlq.head()

✅ DLQ limpio guardado en data/processed/dlq_limpio.csv

      SEQN  DLQ010  DLQ020  DLQ040  DLQ050  DLQ060  DLQ080
0  73557.0     0.0     0.0     0.0     0.0     0.0     0.0
1  73558.0     0.0     0.0     0.0     0.0     0.0     0.0
2  73559.0     1.0     0.0     0.0     0.0     0.0     0.0
3  73560.0     0.0     0.0     0.0     0.0     0.0     0.0
4  73561.0     0.0     0.0     0.0     0.0     0.0     0.0

### Limpieza SLQ_H

In [25]:
# ==========================================
# LIMPIEZA SLQ (Trastornos del sueño)
# ==========================================

import pandas as pd
import numpy as np
from pathlib import Path

# 1) Cargar dataset y seleccionar columnas
slq = pd.read_csv("../data/interim/slq_h_columnas.csv")

SLQ_COLS = ["SEQN", "SLD010H", "SLQ050", "SLQ060"]
slq = slq[SLQ_COLS].copy()

slq.head()

      SEQN  SLD010H  SLQ050  SLQ060
0  73557.0      7.0     1.0     2.0
1  73558.0      9.0     2.0     2.0
2  73559.0      8.0     2.0     2.0
3  73561.0      9.0     2.0     2.0
4  73562.0      5.0     2.0     1.0

In [ ]:
#2 Reemplazar códigos inválidos NHANES
slq["SLD010H"] = slq["SLD010H"].replace([77, 99], np.nan)
slq[["SLQ050", "SLQ060"]] = slq[["SLQ050", "SLQ060"]].replace([7, 9], np.nan)

In [28]:
#3 Convertir variables a formato numerico
for col in SLQ_COLS:
    if col != "SEQN":
        slq[col] = pd.to_numeric(slq[col], errors="coerce")

In [33]:
#4 Limpieza de horas de sueño según codebooK
# Valores válidos: 2–11 horas y 12 = "12 horas o más"
slq["SLD010H"] = slq["SLD010H"].clip(lower=2, upper=12)

# Imputación con mediana
slq["SLD010H"] = slq["SLD010H"].fillna(slq["SLD010H"].median())

In [31]:
#5 Binarizar preguntas SI/NO
slq["SLQ050"] = slq["SLQ050"].map({1: 1, 2: 0})
slq["SLQ060"] = slq["SLQ060"].map({1: 1, 2: 0})

In [34]:
#6 Imputación de valores faltantes (modo)
for col in ["SLQ050", "SLQ060"]:
    slq[col] = slq[col].fillna(slq[col].mode()[0])

In [35]:
slq.to_csv("../data/processed/slq_limpio.csv", index=False)
print("SLQ limpio guardado en data/processed/slq_limpio.csv")

SLQ limpio guardado en data/processed/slq_limpio.csv